### PR TITLE
Initial commit of Foundations of Modern Java Server Apps

### PR DESCRIPTION
**Pull request by kito99**
Initial draft of TUT3720: Foundations of Modern Java Server Apps.

Note that I left the sample chapters in there for now; I'm not sure if I'll be using the lab feature for this, since it's a tutorial, but I may flesh out the introduction page more.

### CODE REVIEW

**Comment by kito99** [comment]
Please note that I have signed the OCA using my current email address.

**Comment by spavlusieva** [comment]
@kito99 yes, we have your signed OCA. Could you make sure that commit author is set to the email address you list in the OCA (kito.mann@virtua.tech)?

**Comment by kito99** [comment]
@spavlusieva OK, will it work if I just change the last commit to have the last email address?

**Comment by spavlusieva** [comment]
@kito99 could you change the email in both commits?

**Comment by kito99** [comment]
@spavlusieva can you take a look now?

**Comment by spavlusieva** [comment]
@kito99 thanks. Please make sure that you use your GitHub username or email you provided in the OCA while signing the commits/PRs. Then the bot will recognise you.

**Review by klazarz — APPROVED** [review]

**Comment by kito99** [comment]
[spavlusieva](https://github.com/spavlusieva) I tried amending the commits, but looks like I still left one in there. I'll ensure the correct email address is there next time.

**Pull request merged**
