### PR TITLE
Create new RMAN Sprints -11316

### PR DESCRIPTION
**Pull request by satish-oracleace**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by william-masdon-oracle** [comment]
Please complete the Oracle Contributor Agreement. We cannot approve your PR before that is done.

**Comment by satish-oracleace** [comment]
Hi ,

I have already signed the agreement.

Thanks
Satish

**Comment by kaylien** [comment]
Hi @satish-oracleace,

The check is still failing on the PR. Are you sure your Oracle account is affiliated with the email committing this PR?

image

Best,
Kaylien

**Comment by satish-oracleace** [comment]
Yes, I use the same email for Oracle account as well.

Can we have a Zoom call to go over and  try to fix the issue?

Thanks
Satish

**Review by kaylien — APPROVED** [review]
The OCA bot seems to have kicked in! I'll cancel our meeting for today

**Comment by satish-oracleace** [comment]
Thanks Kaylien

Once you publish pls let me know

Thanks
Satish

**Pull request merged**
